[package]
name = "vesta_example"
version = "0.1.5"
authors = ["Dominic Maas <dominic.maas@live.com>"]
edition = "2021"

[dependencies]
bevy = "0.8.0"
#smooth-bevy-cameras = "0.4.0"
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras" }
