[package]
name = "vesta"
version = "0.1.0"
authors = ["Dominic Maas <dominic.maas@live.com>"]
edition = "2018"

[dependencies]
winit = "0.24"
wgpu = "0.7"
image = "0.23"
cgmath = "0.18"
bytemuck = { version = "1.5", features = [ "derive" ] }
anyhow = "1.0"

# GUI
imgui = "0.7"
imgui-wgpu = "0.14"
imgui-winit-support = "0.7"

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-19"
features = ["wgsl-in", "spv-out"]