[package]
name = "titan"
version = "0.1.0"
authors = ["Dominic Maas <dominic.maas@live.com>"]
edition = "2021"

[dependencies]
vesta = { path = "../../vesta" }
bracket-noise = "0.8.2"
rand = "0.8"
lagoon = "0.1.3"
